# Run whenever a PR is generated or updated.
name: PicoLlama

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:

  lint:
    name: Arduino library linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: arduino/arduino-lint-action@v2
        with:
          library-manager: 'update'

# Validate orthography, formatting
  code-spell-astyle:
    name: Check spelling and formatting
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Run codespell
      uses: codespell-project/actions-codespell@master
      with:
        skip: ./src/libmad,./src/libhelix-aac,./lib/espeak-ng-arduino,./src/libespeak-ng,./LANGUAGES.md,./test/test_all.py,./model
        ignore_words_list: ESP8266,esp8266,esp,dout,DOUT,ser,ans,inout,numer,hist,aache,TYE,CoO
